import type { Course } from "./subject-section"

export const physicsData: Course[] = [
  {
    id: "physics-1",
    title: "Classical Mechanics",
    description: "Learn the fundamental principles of motion, forces, and energy",
    instructor: "Dr. Richard Feynman",
    level: "Beginner",
    duration: "8 weeks",
    students: 12450,
    rating: 4.8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI-GecsggflqIAAyI0rlsYN3lgn5nPjmN00g&s",
  },
  {
    id: "physics-2",
    title: "Electromagnetism",
    description: "Explore electric and magnetic fields and their applications",
    instructor: "Dr. Marie Curie",
    level: "Intermediate",
    duration: "10 weeks",
    students: 8320,
    rating: 4.7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwfnKoGGekhAdj08vc_kszjgWpAu1s6o4ZFw&s",
  },
  {
    id: "physics-3",
    title: "Quantum Physics",
    description: "Dive into the strange world of quantum mechanics",
    instructor: "Dr. Neil deGrasse Tyson",
    level: "Advanced",
    duration: "12 weeks",
    students: 5640,
    rating: 4.9,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLa1UvNh5Y0hwIpg_JEe448YYmFg3OhNCxKA&s",
  },
  {
    id: "physics-4",
    title: "Thermodynamics",
    description: "Understand heat, energy, and the laws that govern them",
    instructor: "Dr. Lisa Randall",
    level: "Intermediate",
    duration: "8 weeks",
    students: 7890,
    rating: 4.6,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6ANCiYGBSk3bkCTG9QfcOAwpM65Pmv9c8LA&s",
  },
  {
    id: "physics-5",
    title: "Astrophysics",
    description: "Study the physics of stars, galaxies, and the universe",
    instructor: "Dr. Brian Cox",
    level: "Advanced",
    duration: "10 weeks",
    students: 9120,
    rating: 4.8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmSRKKieQcCDXLd8JkNw8b0cXiejoSd4Zr-w&s",
  },
  {
    id: "physics-6",
    title: "Relativity Theory",
    description: "Explore Einstein's revolutionary ideas about space and time",
    instructor: "Dr. Kip Thorne",
    level: "Advanced",
    duration: "8 weeks",
    students: 4560,
    rating: 4.9,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhaCHiiUNxDvj8HRdP29uivbxYDp-bEqpFMg&s",
  },
]

export const pythonData: Course[] = [
  {
    id: "python-1",
    title: "Python Fundamentals",
    description: "Master the basics of Python programming",
    instructor: "Guido van Rossum",
    level: "Beginner",
    duration: "6 weeks",
    students: 24680,
    rating: 4.9,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSFN7H7KvZyI5CGgw0kJfPj_JpEOkyJ3WOeg&s",
  },
  {
    id: "python-2",
    title: "Data Science with Python",
    description: "Learn to analyze and visualize data using Python libraries",
    instructor: "Jake VanderPlas",
    level: "Intermediate",
    duration: "10 weeks",
    students: 18750,
    rating: 4.8,
    image: "https://miro.medium.com/v2/resize:fit:1400/1*LxP1qwPjHE1CDFmLBh3bxQ.jpeg",
  },
  {
    id: "python-3",
    title: "Machine Learning with Python",
    description: "Build intelligent systems using Python's ML libraries",
    instructor: "Andrew Ng",
    level: "Advanced",
    duration: "12 weeks",
    students: 15320,
    rating: 4.9,
    image: "https://pyimagesearch.com/wp-content/uploads/2019/01/python_ml_header.png",
  },
  {
    id: "python-4",
    title: "Web Development with Django",
    description: "Create powerful web applications with Python's Django framework",
    instructor: "Adrian Holovaty",
    level: "Intermediate",
    duration: "8 weeks",
    students: 12450,
    rating: 4.7,
    image: "https://img-c.udemycdn.com/course/750x422/1562632_a245_2.jpg",
  },
]

export const chemistryData: Course[] = [
  {
    id: "chem-1",
    title: "General Chemistry",
    description: "Learn the fundamental principles of chemistry",
    instructor: "Dr. Linus Pauling",
    level: "Beginner",
    duration: "10 weeks",
    students: 14560,
    rating: 4.7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUFtRpUbaNBuOJV1jR2KRXp1KD5I_MZ_CmyQ&s",
  },
  {
    id: "chem-2",
    title: "Organic Chemistry",
    description: "Study carbon-based compounds and their reactions",
    instructor: "Dr. Robert Woodward",
    level: "Intermediate",
    duration: "12 weeks",
    students: 9870,
    rating: 4.6,
    image: "https://i.ytimg.com/vi/-4ZWIkN3zeE/maxresdefault.jpg",
  },,
]

export const languageData: Course[] = [
  {
    id: "lang-1",
    title: "Spanish for Beginners",
    description: "Start your journey to Spanish fluency",
    instructor: "Maria Rodriguez",
    level: "Beginner",
    duration: "12 weeks",
    students: 28760,
    rating: 4.8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQx1nuENYotEx6M3yYUI-YdDNfakissCooRdg&s",
  },
]
